title: I have a dream!
description: > # this means to ignore newlines until "baseurl:"
  Just another boring introverted software developer
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: JOHN KIRAGU # add your name
author-img: kiragu.jpeg # add your photo
about-author: >
  Lover of classic rock music and motorbikes,
  Interested in strongly typed functional programming
  Languages, compiler construction and distributed systems.
  Python and java by day, haskell hacker by night.
  Hoping to learn ocaml and erlang someday
  Join me for when that day finally comes.
social-twitter: kiragu_john
social-facebook: # add your Facebook handle
social-github: kigsmtua # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: mutuakiragu@gmail.com

# Disqus
discus-identifier: johnkiragu

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
